# Generated by Django 4.2.4 on 2023-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('DueDate', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('To do', 'To do'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=100)),
            ],
        ),
    ]
